### ISSUE TITLE
CreateJNLP button

### ISSUE THREAD

**Issue by lastlegion** [sharmalab/TCIAPubHubAdmin#38]
We need to create a CreateJNLP button. It will create a JNLP given a shared list without being associated to a DOI.

**Comment by birm** [comment]
My understanding/solution: Button on admin page clicked, shows field for shared and a button which uploads; on finish, a download link is presented (or it just downloads).

**Comment by birm** [comment]
my draft is here, but it's not working quite right with post
https://gist.github.com/birm/46db0a1929f90497222e742116813bb7

**Comment by birm** [comment]
It's on my branch, but I need to make it look okay, as it still looks quite bad; working on that.

**Comment by birm** [comment]
solved in #41
