### ISSUE TITLE
Add publisher field to stored dois

### ISSUE THREAD

**Issue by birm** [sharmalab/TCIAPubHubAdmin#39]

**Comment by birm** [comment]
not stored currently, will probably need to change bindas?

**Comment by lastlegion** [comment]
No you can send an arbitrary JSON to bindaas/mongo it'll store it as is. We need to make sure we take care of the publisher field while consuming this JSON.

**Comment by birm** [comment]
It looks like it may be omitted intentionally, see it hardcoded in https://github.com/sharmalab/TCIAPubHubAdmin/blob/publisher-1/routes/index.js#L227

**Comment by birm** [comment]
So, I think the question is do we want people to edit publisher on the create form, which they cannot now, or do we want to leave it as is. "The Cancer Imaging Archive" seems to be the publisher in all cases now.

**Comment by birm** [comment]
In #40, I removed the "disabled" attribute from those fields, which should allow it to store. I did not, however, change the createJSON method.
