### ISSUE TITLE
Remove Add Resource button when in Add Resources Page

### ISSUE THREAD

**Issue by sharmaashish** [sharmalab/TCIAPubHubAdmin#5]
When adding a resource, user is presented with a drop down. The Add Resource on that page is confusing. A button should only show up (or become active) once a user selects type

**Comment by lastlegion** [comment]
Fixed in: https://github.com/sharmalab/TCIAPubHubAdmin/commit/f1fe90dc225babdaf437d363c23b2900d2df2119
