### ISSUE TITLE
Add Resources - Type Shared List

### ISSUE THREAD

**Issue by sharmaashish** [sharmalab/TCIAPubHubAdmin#6]
- Remove Resource Name. Resource Name should default to **Images (DICOM)**
- Shared List Name should be renamed to **TCIA Shared List**
- **TCIA Shared List** Should be the first thing
- When adding Shared List resources, rename the **Add Resource** button to **Save Resource**
- Rename the **Submit** button to **Save**

**Comment by lastlegion** [comment]
Fixed in: https://github.com/sharmalab/TCIAPubHubAdmin/commit/f1fe90dc225babdaf437d363c23b2900d2df2119
